/**
 * Parses the agent's summary text into three structured sections and
 * generates a downloadable PDF using jsPDF.
 *
 * Expected section headers in the text (all-caps, on their own lines):
 *   OVERALL SUMMARY
 *   COMMON LEARNING GAPS
 *   STUDENTS NEEDING SUPPORT
 */

export interface ParsedSummary {
  overallSummary: string;
  commonGaps: string;
  studentsNeedingSupport: string;
  raw: string;
}

/** Splits the agent's raw summary text into the three expected sections. */
export function parseSummaryText(raw: string): ParsedSummary {
  const norm = raw.replace(/\r\n/g, '\n').trim();

  // Find each section by its header; everything up to the next header is the content.
  const sections: Record<string, string> = {};
  const headers = [
    'OVERALL SUMMARY',
    'COMMON LEARNING GAPS',
    'STUDENTS NEEDING SUPPORT',
  ];

  for (let i = 0; i < headers.length; i++) {
    const header = headers[i];
    const start = norm.toUpperCase().indexOf(header);
    if (start === -1) continue;

    const contentStart = start + header.length;
    const nextHeader = headers.slice(i + 1).reduce<number>((earliest, h) => {
      const pos = norm.toUpperCase().indexOf(h, contentStart);
      return pos !== -1 && pos < earliest ? pos : earliest;
    }, norm.length);

    sections[header] = norm.slice(contentStart, nextHeader).trim();
  }

  return {
    overallSummary: sections['OVERALL SUMMARY'] ?? '',
    commonGaps: sections['COMMON LEARNING GAPS'] ?? '',
    studentsNeedingSupport: sections['STUDENTS NEEDING SUPPORT'] ?? '',
    raw,
  };
}

/** Generates a PDF from the parsed summary and triggers a browser download. */
export async function downloadSummaryPdf(
  summary: ParsedSummary,
  classroomCode: string,
  teacherName: string,
): Promise<void> {
  // Dynamic import keeps jsPDF out of the initial bundle — only loads when needed.
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addWrappedText = (
    text: string,
    x: number,
    startY: number,
    maxWidth: number,
    lineHeight: number,
  ): number => {
    const lines = doc.splitTextToSize(text, maxWidth) as string[];
    doc.text(lines, x, startY);
    return startY + lines.length * lineHeight;
  };

  // ── Title ──────────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('SonaAI — Class Summary', margin, y);
  y += 10;

  // ── Metadata ───────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });
  doc.text(`Date: ${dateStr} at ${timeStr}`, margin, y);
  y += 5;
  doc.text(`Teacher: ${teacherName}`, margin, y);
  y += 5;
  doc.text(`Classroom code: ${classroomCode}`, margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  doc.setTextColor(0);

  // ── Section helper ─────────────────────────────────────────────────────────
  const addSection = (title: string, body: string): void => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(title, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const content = body.trim() || 'None identified.';
    y = addWrappedText(content, margin, y, contentWidth, 6);
    y += 8;
  };

  addSection('Overall Summary', summary.overallSummary);
  addSection('Common Learning Gaps', summary.commonGaps);
  addSection('Students Needing Support', summary.studentsNeedingSupport);

  // ── Footer ─────────────────────────────────────────────────────────────────
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by SonaAI Co-teacher', margin, pageHeight - 10);

  // Trigger download
  const filename = `sonaai-summary-${classroomCode}-${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
